AUG:
  COLOR_AUG: 0.25
  RANDOM_ANOMALY: true
  RANDOM_CROP_PROB: 0.5
  SCALE_MAX: 2.0
  SCALE_MIN: 0.5
DATASET:
  FULL_DATA: false
  PERSPECTIVE_AUG: true
  ROAD_ROI_ONLY: true
  TEST: LaF
  TRAIN: citybdd100k_2class
  VAL: LaF
EXPERIMENT:
  EPOCHS: 100
  EVAL_INTERVAL: 1
  EVAL_METRIC: AnomalyEvaluator
  EVAL_USE_METRIC: true
  NAME: '20220302_152340_166710'
  OUT_DIR: ./training/experiments/
  RESUME_CHECKPOINT: null
  START_EPOCH: 0
INPUT:
  BASE_SIZE: 896
  BATCH_SIZE_TEST: 2
  BATCH_SIZE_TRAIN: 2
  CROP_SIZE: 896
  NORM_MEAN:
  - 0.485
  - 0.456
  - 0.406
  NORM_STD:
  - 0.229
  - 0.224
  - 0.225
LOSS:
  BATCH_AVG: true
  DIRECTION_TRIPLET_REGULARIZATION: 0.2
  EMBEDDING_MARGIN: 1
  EMB_SPACE_REG: 50.0
  EMB_SPACE_REG_WEIGHT: 0.0
  HARD_NEGATIVE_START_EPOCH: -1
  IGNORE_LABEL: 255
  SIZE_AVG: true
  TYPE: GlobalOnlyDecL2TripletMarginLossXentCoupeling
  WARM_UP_DYNAMIC_WEIGHTS: true
  XENT_MARGIN_REG: false
MODEL:
  BACKBONE: resnet
  FREEZE_BN: false
  INPAINT_WEIGHTS_FILE: <ABSOLUTE PATH TO>/deepfillv2_WGAN_G_epoch40_batchsize4.pth
  LOCAL_RECONSTRUCTION:
    EMBEDDING_DIM: 16
    LATENT_DIM_PER_SCALE: 128
    SKIP_CONN: true
  NET: DeepLabEmbeddingGlobalOnlySegmFullResInpaint_wide
  OUT_STRIDE: 16
  RECONSTRUCTION:
    BLUR_IMG: true
    ERROR_FNC: ssim
    INTERPOLATION: bilinear
    LATENT_DIM: 4
    SEGM_MODEL: <ABSOLUTE PAT TO>/checkpoint-segmentation.pth
    SEGM_MODEL_NCLASS: 19
    SKIP_CONN: true
    SKIP_CONN_DIM: 32
  SYNC_BN: false
OPTIMIZER:
  LR: 0.001
  LR_SCHEDULER: poly
  MOMENTUM: 0.9
  NESTEROV: false
  WEIGHT_DECAY: 0.0005
SYSTEM:
  GPU_IDS:
  - 0
  NUM_CPU: 4
  RNG_SEED: 42
  USE_GPU: true
